eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/

server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost/realms/BookLibrary

logging:
  level:
    ROOT: ERROR
    ru.otus.mar: DEBUG
    #org.springframework.security: DEBUG
