server:
  port: 8080

eureka:
  instance:
    hostName: ${spring.application.name}
    preferIpAddress: true
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

spring:
  cloud:
    gateway:
      #discovery.locator.enabled: true
      routes:
        - id: web
          uri: http://web
          predicates:
            - Path=/web/**
        - id: api
          uri: lb://booklibrary-microservice
          predicates:
            - Path=/api/**,/swagger-ui/**,/v3/**,/actuator/**
        - id: root
          uri: http://web
          predicates:
            - Path=/
          #https://www.baeldung.com/spring-cloud-gateway-url-rewriting
          filters:
            - RewritePath=/, /web/book.html
#log
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true

management:
  server:
    port: ${server.port}
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
