eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

spring:
  cloud:
    gateway:
      routes:
        - id: web
          uri: http://web
          predicates:
            - Path=/web/**
        - id: api
          uri: lb://booklibrary-microservice
          predicates:
            - Path=/api/**,/swagger-ui/**,/v3/**,/actuator/**
        - id: root
          uri: http://web
          predicates:
            - Path=/
          #https://www.baeldung.com/spring-cloud-gateway-url-rewriting
          filters:
            - RewritePath=/, /web/book.html
