spring:
  data:
    mongodb:
      database: booklibrary
      port: 27017
      host: localhost
      #auto-index-creation: true

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.mar.booklibrary.mongock.changelog

logging:
  level:
    org.springframework: ERROR
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
              convert:
                MongoDatabaseFactoryReferenceLoader: TRACE