server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

logging:
  level:
    ROOT: ERROR
    ru.otus.mar.booklibrary: DEBUG
