version: "3.3"
services:

  db:
    image: postgres:14.7-alpine
    container_name: db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db

  sso:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: sso
    #http://localhost:8084/realms/BookLibrary/hostname-debug
    command:
      - start-dev --hostname-debug=true
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      #KEYCLOAK_IMPORT: /tmp/realm-export.json
      #PROXY_ADDRESS_FORWARDING: "true"
      KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/tls.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/tls.key
    volumes:
      - ./sso-server/volume/h2/:/opt/keycloak/data/h2/
      #- ./sso-server/realm-export.json:/tmp/realm-export.json
      - ./sso-server/cert/sso.crt.pem:/etc/x509/https/tls.crt
      - ./sso-server/cert/sso.key.pem:/etc/x509/https/tls.key
    ports:
      - 8080:8080
      - 8443:8443

  config:
    container_name: config
    build:
      context: config-server
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: native
      DISCOVERY_URL: http://discovery:8761/eureka/
    ports:
      - "8888:8888"

  discovery:
    container_name: discovery
    build:
      context: discovery-server
      dockerfile: Dockerfile
    environment:
      CONFIG_URL: http://config:8888/
      CONFIG_LABEL: default
    ports:
      - "8761:8761"
    restart: always
    depends_on:
      - config

  gateway:
    container_name: gateway
    build:
      context: gateway-server
      dockerfile: Dockerfile
    environment:
      CONFIG_URL: http://config:8888/
      CONFIG_LABEL: default
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: DEBUG
      #--- iframe
      #SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8081:8080"
    restart: always
    depends_on:
      - config
      - discovery
      - sso
    #extra_hosts:
      #- "host.docker.internal:host-gateway"

  booklibrary:
    container_name: booklibrary
    build:
      context: booklibrary-microservice
      dockerfile: Dockerfile
    environment:
      - CONFIG_URL=http://config:8888/
      - CONFIG_LABEL=default
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      #- SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - config
      - db

  notification:
    container_name: notification
    build:
      context: notification-microservice
      dockerfile: Dockerfile
    environment:
      - CONFIG_URL=http://config:8888/
      - CONFIG_LABEL=default
    depends_on:
      - config

  web:
    container_name: web
    build:
      context: web-client
      dockerfile: Dockerfile
    ports:
      - "80:80"

  #--- iframe
  reverse-proxy:
    image: nginx:1.25.2-alpine
    container_name: reverse-proxy
    volumes:
      - ./reverse-proxy/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8084:8080
